
# This file was *autogenerated* from the file ki.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16)
BIN = GF(_sage_const_16 )['X']; (X,) = BIN._first_ngens(1)
B = GF(_sage_const_2 )['X']; (X,) = B._first_ngens(1)
while _sage_const_1 :
      poly = BIN.random_element(_sage_const_8 );
      if poly.is_irreducible():
      	 break;
print(poly)
 

